# Generated by Django 5.0.2 on 2024-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_ingredient_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="alias",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
