# Generated by Django 5.0.2 on 2024-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_product_unique_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0.0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
