# Generated by Django 5.0.2 on 2024-03-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_product_rating_alter_product_unique_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="num_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
