# Generated by Django 5.0.2 on 2024-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_product_num_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="avoid_list",
            field=models.ManyToManyField(blank=True, to="backend.ingredient"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="caution_list",
            field=models.ManyToManyField(blank=True, to="backend.ingredient"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="incidecoder_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
