# Generated by Django 5.0.2 on 2024-03-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_ingredient_avoid_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="unique_identifier",
        ),
        migrations.AlterField(
            model_name="brand",
            name="img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_active",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_active",
                to="backend.ingredient",
            ),
        ),
    ]
