# Generated by Django 5.0.2 on 2024-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0009_remove_product_unique_identifier_alter_brand_img_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unique_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
