# Generated by Django 5.0.2 on 2024-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_product_unique_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unique_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
