# Generated by Django 5.0.2 on 2024-03-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_product_unique_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="incidecoder_url",
            field=models.URLField(blank=True, default="/", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="unique_identifier",
            field=models.CharField(
                blank=True, editable=False, max_length=255, unique=True
            ),
        ),
    ]
