# Generated by Django 5.0.2 on 2024-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_alter_ingredient_incidecoder_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="incidecoder_url",
            field=models.URLField(default="/", unique=True),
        ),
    ]
