# Generated by Django 5.0.2 on 2024-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_ingredient_incidecoder_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
