# Generated by Django 5.0.2 on 2024-03-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                default=40,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.brand",
            ),
            preserve_default=False,
        ),
    ]
