# Generated by Django 5.0.2 on 2024-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_brand_slug_alter_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="main_active",
        ),
        migrations.AddField(
            model_name="product",
            name="main_active",
            field=models.ManyToManyField(
                blank=True, related_name="main_active", to="backend.ingredient"
            ),
        ),
    ]
