# Generated by Django 5.0.2 on 2024-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_profile_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="skin_concern",
        ),
        migrations.RemoveField(
            model_name="product",
            name="skin_concern",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="skinconcern",
            name="ingredients",
            field=models.ManyToManyField(blank=True, to="backend.ingredient"),
        ),
    ]
