# Generated by Django 5.0.2 on 2024-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0018_remove_ingredient_skin_concern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skinconcern",
            name="slugified_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
