# Generated by Django 5.0.2 on 2024-04-02 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_remove_schedule_user_schedule_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="product",
            new_name="products",
        ),
    ]
