# Generated by Django 5.0.2 on 2024-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_rename_product_schedule_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="own_list",
        ),
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to="backend.product"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="purchased",
            field=models.ManyToManyField(
                blank=True, related_name="purchased", to="backend.product"
            ),
        ),
    ]
